node {
  stage ('Build') {
    git url: 'https://github.com/cyrille-leclerc/multi-module-maven-project'
    withMaven {
      sh "mvn clean verify"
    } // withMaven will discover the generated Maven artifacts, JUnit Surefire & FailSafe reports and FindBugs reports
  }

  stage('SonarQube analysis') {

        withSonarQubeEnv{

            sh 'mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=01934431c1546f26c068f7a91e4bf065e8097d28'

        }

    }


}